/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Luis13 (https://sketchfab.com/luis230799)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/peachs-castle-super-mario-f609112d34b74fb99971b92ead5a07f0
Title: Peach's Castle - Super Mario
*/
/*
import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import castleScene from "../assets/3d/castle.glb";

const Castle = (props) => {
  const { nodes, materials } = useGLTF("/peachs_castle_-_super_mario.glb");
  return (
*/